Xippogmbh\XippoErpCoreBundle\Entity\Communicationtype:
    type: entity
    table: CommunicationTypes
    indexes:
        IDX_A74516CB307128E3:
            columns:
                - formatTypeFID
        IDX_A74516CBD490A9DD:
            columns:
                - textFID
    id:
        communicationTypeID:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: communicationTypeID
            generator:
                strategy: IDENTITY
    fields:
        icon:
            type: blob
            nullable: true
            length: null
            options:
                fixed: false
    manyToOne:
        formatTypeFID:
            targetEntity: FormatType
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                formatTypeFID:
                    referencedColumnName: formatTypeID
            orphanRemoval: false
        textFID:
            targetEntity: Text
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                textFID:
                    referencedColumnName: textID
            orphanRemoval: false
    lifecycleCallbacks: {  }
