Xippogmbh\XippoErpCoreBundle\Entity\Employee:
    type: entity
    table: Employees
    indexes:
        IDX_387341A385391DE3:
            columns:
                - currencyFID
        IDX_387341A3D1D903EC:
            columns:
                - rateUnitFID
        IDX_387341A369BA2137:
            columns:
                - subsidiaryFID
        IDX_387341A33FEC2661:
            columns:
                - languageFID
        IDX_387341A348AA33E0:
            columns:
                - addressFID
    uniqueConstraints:
        IX_EmployeesUserName:
            columns:
                - userName
    id:
        employeeID:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: employeeID
            generator:
                strategy: IDENTITY
    fields:
        canLogin:
            type: boolean
            nullable: false
            column: canLogin
        createDate:
            type: datetime
            nullable: false
            column: createDate
        createUser:
            type: string
            nullable: false
            length: 60
            options:
                fixed: false
            column: createUser
        exchangeUser:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: exchangeUser
        hasCalendar:
            type: boolean
            nullable: false
            column: hasCalendar
        hasLDAP:
            type: boolean
            nullable: false
            column: hasLDAP
        holidays:
            type: decimal
            nullable: true
            precision: 18
            scale: 2
        isActive:
            type: boolean
            nullable: false
            column: isActive
        modifyDate:
            type: datetime
            nullable: false
            column: modifyDate
        modifyUser:
            type: string
            nullable: false
            length: 60
            options:
                fixed: false
            column: modifyUser
        password:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        rate:
            type: integer
            nullable: true
            options:
                unsigned: false
        salery:
            type: integer
            nullable: true
            options:
                unsigned: false
        userName:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: userName
    manyToOne:
        currencyFID:
            targetEntity: Currency
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                currencyFID:
                    referencedColumnName: currencyID
            orphanRemoval: false
        rateUnitFID:
            targetEntity: Unit
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                rateUnitFID:
                    referencedColumnName: unitID
            orphanRemoval: false
        subsidiaryFID:
            targetEntity: Subsidiary
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                subsidiaryFID:
                    referencedColumnName: subsidiaryID
            orphanRemoval: false
        languageFID:
            targetEntity: Language
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                languageFID:
                    referencedColumnName: languageID
            orphanRemoval: false
        addressFID:
            targetEntity: Address
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                addressFID:
                    referencedColumnName: addressID
            orphanRemoval: false
    lifecycleCallbacks: {  }
