Xippogmbh\XippoErpCoreBundle\Entity\Subsidiary:
    type: entity
    table: Subsidiarys
    indexes:
        IDX_3086E46348AA33E0:
            columns:
                - addressFID
    id:
        subsidiaryID:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: subsidiaryID
            generator:
                strategy: IDENTITY
    manyToOne:
        addressFID:
            targetEntity: Address
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                addressFID:
                    referencedColumnName: addressID
            orphanRemoval: false
    lifecycleCallbacks: {  }
