Xippogmbh\XippoErpCoreBundle\Entity\Text:
    type: entity
    table: Texts
    indexes:
        IDX_DFF43CBB3FEC2661:
            columns:
                - languageFID
    id:
        textID:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: textID
            generator:
                strategy: IDENTITY
    fields:
        longText:
            type: string
            nullable: true
            length: 0
            options:
                fixed: false
            column: longText
        text:
            type: string
            nullable: true
            length: 60
            options:
                fixed: false
    manyToOne:
        languageFID:
            targetEntity: Language
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                languageFID:
                    referencedColumnName: languageID
            orphanRemoval: false
    lifecycleCallbacks: {  }
