Xippogmbh\XippoErpCoreBundle\Entity\Currency:
    type: entity
    table: Currencys
    indexes:
        IDX_2FF0361D82B16694:
            columns:
                - currencyLinkFID
        IDX_2FF0361DD490A9DD:
            columns:
                - textFID
    id:
        currencyID:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: currencyID
            generator:
                strategy: IDENTITY
    fields:
        isoCode:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
            column: isoCode
        round:
            type: decimal
            nullable: false
            precision: 18
            scale: 2
        tolerance:
            type: decimal
            nullable: false
            precision: 18
            scale: 2
    manyToOne:
        currencyLinkFID:
            targetEntity: Currency
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                currencyLinkFID:
                    referencedColumnName: currencyID
            orphanRemoval: false
        textFID:
            targetEntity: Text
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                textFID:
                    referencedColumnName: textID
            orphanRemoval: false
    lifecycleCallbacks: {  }
