Xippogmbh\XippoErpCoreBundle\Entity\Language:
    type: entity
    table: Languages
    id:
        languageID:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: languageID
            generator:
                strategy: IDENTITY
    fields:
        langISOlong:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
            column: langISOlong
        langISOshort:
            type: string
            nullable: false
            length: 2
            options:
                fixed: false
            column: langISOshort
    lifecycleCallbacks: {  }
