Xippogmbh\XippoErpCoreBundle\Entity\Salutation:
    type: entity
    table: Salutations
    id:
        salutationID:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: salutationID
            generator:
                strategy: IDENTITY
    fields:
        addressSalutation:
            type: string
            nullable: false
            length: 60
            options:
                fixed: false
                default: ''
            column: addressSalutation
        addressSalutationReplace:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
                default: ''
            column: addressSalutationReplace
        letterSalutation:
            type: string
            nullable: false
            length: 60
            options:
                fixed: false
                default: ''
            column: letterSalutation
        letterSalutationReplace:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
                default: ''
            column: letterSalutationReplace
    lifecycleCallbacks: {  }
